const ActionTypes = {
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    ADD_TO_SELECTED_INGREDIENTS: 'ADD_TO_SELECTED_INGREDIENTS',
    REMOVE_FROM_SELECTED_INGREDIENTS: 'REMOVE_FROM_SELECTED_INGREDIENTS',
    FILTER_INGREDIENTS: 'FILTER_INGREDIENTS',
    SET_COCKTAILS: 'SET_COCKTAILS',
    SET_SELECTED_COCKTAIL: 'SET_SELECTED_COCKTAIL',
};

export default ActionTypes;
