const ActionTypes = {
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    ADD_TO_SELECTED_INGREDIENTS: 'ADD_TO_SELECTED_INGREDIENTS',
    REMOVE_FROM_SELECTED_INGREDIENTS: 'REMOVE_FROM_SELECTED_INGREDIENTS',
};

export default ActionTypes;
